// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fDq6gJ8x1S0UE8NzGjP9BNbwcbiMrWw',
    appId: '1:329848945484:web:c5d91df4aaf3d1212bede9',
    messagingSenderId: '329848945484',
    projectId: 'make-your-body',
    authDomain: 'make-your-body.firebaseapp.com',
    storageBucket: 'make-your-body.firebasestorage.app',
    measurementId: 'G-XMH6B3YE6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8opaUl8-BG1RdBASMIsFOYta7h20L0c',
    appId: '1:329848945484:android:4d3f98ab79fc52ed2bede9',
    messagingSenderId: '329848945484',
    projectId: 'make-your-body',
    storageBucket: 'make-your-body.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquRpvV7VNOXoo2cI9BIvaNKm6FMxEEnY',
    appId: '1:329848945484:ios:2d10ef38f58d6f762bede9',
    messagingSenderId: '329848945484',
    projectId: 'make-your-body',
    storageBucket: 'make-your-body.firebasestorage.app',
    iosBundleId: 'com.example.projetoApp',
  );
}
